def transform(self, jam):
        '''Bypass transformations.

        Parameters
        ----------
        jam : pyjams.JAMS
            A muda-enabled JAMS object

        Yields
        ------
        jam_out : pyjams.JAMS iterator
            The first result is `jam` (unmodified), by reference
            All subsequent results are generated by `transformer`
        '''
        # Step 1: yield the unmodified jam
        yield jam

        # Step 2: yield from the transformer
        for jam_out in self.transformer.transform(jam):
            yield jam_out