def getInferenceTypeFromLabel(cls, label):
    """ 
    Extracts the PredictionKind (temporal vs. nontemporal) from the given
    metric label.

    :param label: (string) for a metric spec generated by 
           :meth:`getMetricLabel`

    :returns: (:class:`~nupic.frameworks.opf.opf_utils.InferenceType`)
    """
    infType, _, _= label.partition(cls._LABEL_SEPARATOR)

    if not InferenceType.validate(infType):
      return None

    return infType