def do_menu(self, line):
        """Display a menu of command-line options. Command syntax is: menu"""
        print('\tchan_log_all\tSet the channel log level to ALL_COMMS.')
        print('\tchan_log_normal\tSet the channel log level to NORMAL.')
        print('\tdisable_unsol\tPerform the function DISABLE_UNSOLICITED.')
        print('\thelp\t\tDisplay command-line help.')
        print('\tmast_log_all\tSet the master log level to ALL_COMMS.')
        print('\tmast_log_normal\tSet the master log level to NORMAL.')
        print('\tmenu\t\tDisplay this menu.')
        print('\to1\t\tSend a DirectOperate LATCH_ON command.')
        print('\to2\t\tSend a DirectOperate analog value.')
        print('\to3\t\tSend a DirectOperate CommandSet.')
        print('\tquit')
        print('\trestart\t\tRequest an outstation cold restart.')
        print('\ts1\t\tSend a SelectAndOperate LATCH_ON command.')
        print('\ts2\t\tSend a SelectAndOperate CommandSet.')
        print('\tscan_all\tRead data from the outstation (ScanAllObjects).')
        print('\tscan_fast\tDemand immediate execution of the fast (every 1 mins) Class 1 scan.')
        print('\tscan_range\tPerform an ad-hoc scan (ScanRange) of GroupVariation 1.2, range 0..3.')
        print('\tscan_slow\tDemand immediate execution of the slow (every 30 mins) All-Classes scan.')
        print('\twrite_time\tWrite a TimeAndInterval to the outstation.')